---
name: HTML-Template-Compiled-Filter-Whitespace
version: 0.07
author:
  - 'Steffen Winkler <steffenw at cpan.org>, Volker Voit <volker.voit at googlemail.com>'
abstract: 'HTML::Template::Compiled::Filter::Whitespace - whitespace filter for HTML output'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Perl6::Export::Attrs: 0
  perl: 5.006001
build_requires:
  Test::NoWarnings: 0
  Test::Simple: 0
recommends:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  HTML::Template::Compiled::Filter::Whitespace:
    file: lib/HTML/Template/Compiled/Filter/Whitespace.pm
    version: 0.07
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
