---
name: HTML-Template-Compiled-Filter-Whitespace
version: 0.04
author:
  - 'Steffen Winkler - steffenw@cpan.org, Volker Voit - volker.voit@googlemail.com'
abstract: whitespace filter for HTML output
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Perl6::Export::Attrs: 0
build_requires:
  Test::More: 0
provides:
  HTML::Template::Compiled::Filter::Whitespace:
    file: lib/HTML/Template/Compiled/Filter/Whitespace.pm
    version: 0.04
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
